# -*- coding: utf-8 -*-
"""Palette data shared with the IntelliJ IDEA schemes of the sibling project.

GENERATED by idea_themes/extract_palettes.py -- do not edit by hand.

It bakes in the values the IDEA side produces: its palette tables plus the
readability pass that converges roles appearing on several backgrounds at once.
Baking them keeps this repository standalone (it imports nothing from outside).
If a colour changes there, re-run that script and this file follows.
"""

import colorsys
import os

PALETTES = {   'Kurumi Tokisaki Dark': {   'dark': True,
                                'parent': 'Darcula',
                                'win': '#1E1C22',
                                'panel': '#26232E',
                                'raised': '#2E2B36',
                                'hover': '#3A3644',
                                'border': '#43404E',
                                'fg': '#D8D4DE',
                                'fg2': '#B8B4C2',
                                'fg3': '#8E8A98',
                                'sel': '#4A2430',
                                'accent': '#E8604F',
                                'gold': '#E0A838',
                                'info': '#7AB8E8',
                                'err': '#FF4D4D',
                                'warn': '#D8A03C',
                                'errBg': '#5E2A36',
                                'warnBg': '#4A3A1E',
                                'infoBg': '#14293C',
                                'overlay': '#FFFFFF1A',
                                'onAccent': '#1E1C22',
                                'onGold': '#1E1C22'},
    'Kurumi Tokisaki Light': {   'dark': False,
                                 'parent': 'IntelliJ',
                                 'win': '#FBF9F7',
                                 'panel': '#F4F0ED',
                                 'raised': '#FFFFFF',
                                 'hover': '#EDE7E3',
                                 'border': '#DED7D3',
                                 'fg': '#2B2933',
                                 'fg2': '#4A4650',
                                 'fg3': '#8A858F',
                                 'sel': '#F6D9D4',
                                 'accent': '#B03A22',
                                 'gold': '#8C6414',
                                 'info': '#2E6E9E',
                                 'err': '#D6192F',
                                 'warn': '#a15e00',
                                 'errBg': '#F8DCD8',
                                 'warnBg': '#F3E7D4',
                                 'infoBg': '#E4F0F8',
                                 'overlay': '#00000012',
                                 'onAccent': '#FFFFFF',
                                 'onGold': '#FFFFFF'},
    'Hatsune Miku Dark': {   'dark': True,
                             'parent': 'Darcula',
                             'win': '#0B1A2A',
                             'panel': '#102436',
                             'raised': '#16304A',
                             'hover': '#1D3D5C',
                             'border': '#22496E',
                             'fg': '#C0D6E4',
                             'fg2': '#9EBDD0',
                             'fg3': '#5A7B95',
                             'sel': '#1B4A6E',
                             'accent': '#48C0F8',
                             'gold': '#F0B8CC',
                             'info': '#48C0F8',
                             'err': '#FF5F56',
                             'warn': '#E8B84A',
                             'errBg': '#5E2A36',
                             'warnBg': '#3E3418',
                             'infoBg': '#14293C',
                             'overlay': '#FFFFFF1A',
                             'onAccent': '#0B1A2A',
                             'onGold': '#0B1A2A'},
    'Hatsune Miku Light': {   'dark': False,
                              'parent': 'IntelliJ',
                              'win': '#FBF7FA',
                              'panel': '#F4EFF5',
                              'raised': '#FFFFFF',
                              'hover': '#EAE3EF',
                              'border': '#DBD2E0',
                              'fg': '#2A3B45',
                              'fg2': '#3D5A6B',
                              'fg3': '#758ea0',
                              'sel': '#D6EBFA',
                              'accent': '#0772b8',
                              'gold': '#B05C7A',
                              'info': '#005EA8',
                              'err': '#d12c2c',
                              'warn': '#a15e00',
                              'errBg': '#F8E0E6',
                              'warnBg': '#F3E7D4',
                              'infoBg': '#E4F0F8',
                              'overlay': '#00000012',
                              'onAccent': '#FFFFFF',
                              'onGold': '#FFFFFF'}}

EDITOR_ROLES = {   'Kurumi Tokisaki Light': {   'keyword': '#8C6414',
                                 'string': '#B03A22',
                                 'number': '#982850',
                                 'comment': '#6e7580',
                                 'predefined': '#7A2E4A',
                                 'escape': '#AC601C',
                                 'operator': '#6A646C',
                                 'doc_tag': '#8C6414',
                                 'soft_keyword': '#8C6414'},
    'Kurumi Tokisaki Dark': {   'keyword': '#E0A838',
                                'string': '#E8604F',
                                'number': '#E8C870',
                                'comment': '#8E959E',
                                'predefined': '#F0A878',
                                'escape': '#F0A878',
                                'operator': '#8E8A98',
                                'doc_tag': '#E0A838',
                                'soft_keyword': '#E0A838'},
    'Hatsune Miku Light': {   'keyword': '#0777BF',
                              'string': '#1D8169',
                              'number': '#B2593B',
                              'comment': '#5c7a91',
                              'predefined': '#005EA8',
                              'escape': '#B2593B',
                              'operator': '#5C7681',
                              'doc_tag': '#0777BF',
                              'soft_keyword': '#0777BF'},
    'Hatsune Miku Dark': {   'keyword': '#48C0F8',
                             'string': '#F0B8CC',
                             'number': '#A8E8F0',
                             'comment': '#6386a1',
                             'predefined': '#5FD0C0',
                             'escape': '#A8E8F0',
                             'operator': '#6E90A8',
                             'doc_tag': '#48C0F8',
                             'soft_keyword': '#48C0F8'}}


# --------------------------------------------------------------- helpers ----
def _rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def _lum(h):
    def lin(c):
        c = c / 255.0
        return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4
    r, g, b = _rgb(h)
    return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b)


def contrast(c1, c2):
    a, b = _lum(c1), _lum(c2)
    return round((max(a, b) + 0.05) / (min(a, b) + 0.05), 2)


def _hls_hex(h, l, s):
    r, g, b = colorsys.hls_to_rgb(h, l, s)
    return "#{:02x}{:02x}{:02x}".format(
        max(0, min(255, round(r * 255))),
        max(0, min(255, round(g * 255))),
        max(0, min(255, round(b * 255))))


def adjust(fg, bg, target):
    """Nudge lightness only, until fg/bg meets the contrast target.

    The direction moves away from the background rather than assuming a light or
    dark theme, because several backgrounds here are mid-tone (gold, vermilion).
    """
    if not bg or contrast(fg, bg) >= target:
        return fg
    r, g, b = _rgb(fg)
    h, l, s = colorsys.rgb_to_hls(r / 255.0, g / 255.0, b / 255.0)
    brighter = _lum(fg) >= _lum(bg)
    lo, hi = (l, 1.0) if brighter else (0.0, l)
    for _ in range(48):
        mid = (lo + hi) / 2.0
        if contrast(_hls_hex(h, mid, s), bg) >= target:
            hi, lo = (mid, lo) if brighter else (hi, mid)
        else:
            lo, hi = (mid, hi) if brighter else (lo, mid)
    found = _hls_hex(h, hi if brighter else lo, s)
    if contrast(found, bg) < target:
        for cand in ("#ffffff", "#000000", _hls_hex(h, 1.0 if brighter else 0.0, s)):
            if contrast(cand, bg) >= target:
                return cand
    return found


# ------------------------------------------------------ preview rendering ----
FONT_DIR = "C:/Windows/Fonts"
FACES = {
    0: ("consola.ttf", "consolab.ttf"),
    1: ("consolab.ttf", "consolab.ttf"),
    2: ("consolai.ttf", "consolaz.ttf"),
    3: ("consolaz.ttf", "consolaz.ttf"),
}


def hx(v):
    """The preview's drawing layer wants a leading '#'; the tables store bare hex."""
    if not v:
        return None
    return v if v.startswith("#") else "#" + v


def rgb(v):
    h = hx(v).lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def load_font(font_type, size=15, bold=False):
    from PIL import ImageFont
    key = 1 if bold else font_type
    reg, _bold = FACES.get(key, FACES[0])
    try:
        return ImageFont.truetype(os.path.join(FONT_DIR, reg), size)
    except OSError:
        return ImageFont.load_default()
